// Generated by CoffeeScript 1.6.3
var Card, CardContainer, cards_global, scrollHandler;

cards_global = {
  card_container: null,
  card_width: 250
};

/*
	Classes and such
*/


Card = (function() {
  function Card(elem, title, imageURL) {
    this.elem = elem;
    this.title = title;
    this.imageURL = imageURL;
  }

  Card.prototype.render = function() {};

  return Card;

})();

CardContainer = (function() {
  function CardContainer(elem, cards) {
    this.elem = elem;
    this.cards = cards;
  }

  CardContainer.prototype.setContainerWidth = function() {
    var width;
    width = this.cards.length * 252;
    this.elem.width(width + 200);
  };

  return CardContainer;

})();

/*
	Set Up Application
*/


scrollHandler = function(scrollEvent) {
  var newLeftMargin, oldLeftMargin;
  oldLeftMargin = parseInt($(".card-container").first().css("margin-left"), 10);
  newLeftMargin = oldLeftMargin - scrollEvent.deltaY / 5;
  $(".card-container").first().css("margin-left", newLeftMargin + "px");
};

$(document).ready(function() {
  var cards;
  cards = [];
  $(".card").each(function(card_elem) {
    var card;
    card = new Card(card_elem, "Llama", "http://twistedrootburgerco.com/wp-content/uploads/Llama.jpg");
    return cards.push(card);
  });
  cards_global.card_container = new CardContainer($(".card-container"), cards);
  cards_global.card_container.setContainerWidth();
  window.addEventListener("wheel", scrollHandler);
});
