// Generated by CoffeeScript 1.6.3
var Card, CardContainer, cards_global, scrollHandler, updateScroll;

cards_global = {
  card_container: null,
  card_width: 250,
  scroll_speed: 0,
  MAX_SPEED: 10,
  is_scrolling: false,
  timer_id: -1
};

/*
	Classes and such
*/


Card = (function() {
  function Card(elem, title, imageURL) {
    this.elem = elem;
    this.title = title;
    this.imageURL = imageURL;
  }

  Card.prototype.render = function() {};

  return Card;

})();

CardContainer = (function() {
  function CardContainer(elem, cards) {
    this.elem = elem;
    this.cards = cards;
  }

  CardContainer.prototype.setContainerWidth = function() {
    var width;
    width = this.cards.length * 252;
    this.elem.width(width + 200);
  };

  return CardContainer;

})();

/*
	Set Up Application
*/


scrollHandler = function(scrollEvent) {
  if (!Math.abs(cards_global.scroll_speed > cards_global.MAX_SPEED)) {
    cards_global.scroll_speed += scrollEvent.deltaX / 5;
  }
  if (!cards_global.is_scrolling) {
    cards_global.timer_id = setInterval(updateScroll, 500);
  }
};

updateScroll = function() {
  var newLeftMargin, oldLeftMargin;
  oldLeftMargin = parseInt($(".card-container").first().css("margin-left"), 10);
  newLeftMargin = oldLeftMargin - cards_global.scroll_speed;
  $(".card-container").first().css("margin-left", newLeftMargin + "px");
  if (cards_global.scroll_speed > 0) {
    if (cards_global.scroll_speed < 0.1) {
      cards_global.scroll_speed = 0;
    } else {
      cards_global.scroll_speed -= 0.1;
    }
  } else {
    if (cards_global.scroll_speed > -0.1) {
      cards_global.scroll_speed = 0;
    } else {
      cards_global.scroll_speed += 0.1;
    }
  }
  if (cards_global.scroll_speed < 1 && cards_global.scroll_speed > -1) {
    clearInterval(cards_global.timer_id);
    cards_global.scroll_speed = 0;
    cards_global.timer_id = -1;
  }
};

$(document).ready(function() {
  var cards;
  cards = [];
  $(".card").each(function(card_elem) {
    var card;
    card = new Card(card_elem, "Llama", "http://twistedrootburgerco.com/wp-content/uploads/Llama.jpg");
    return cards.push(card);
  });
  cards_global.card_container = new CardContainer($(".card-container"), cards);
  cards_global.card_container.setContainerWidth();
  window.addEventListener("wheel", scrollHandler);
});
