// Generated by CoffeeScript 1.6.3
var Card, CardContainer, cards_global;

cards_global = {
  card_container: null,
  card_width: 250
};

$(document).ready(function() {
  var cards;
  console.log("Page Ready");
  cards = [];
  $(".card").each(function(card_elem) {
    var card;
    card = new Card(card_elem, "Llama", "http://twistedrootburgerco.com/wp-content/uploads/Llama.jpg");
    return cards.push(card);
  });
  cards_global = new CardContainer($(".card-container"), cards);
  console.log(cards.length);
});

Card = (function() {
  function Card(elem, title, imageURL) {
    this.elem = elem;
    this.title = title;
    this.imageURL = imageURL;
  }

  Card.prototype.render = function() {};

  return Card;

})();

CardContainer = (function() {
  function CardContainer(elem, cards) {
    this.elem = elem;
    this.cards = cards;
  }

  CardContainer.prototype.setContainerWidth = function() {
    var width;
    width = this.cards.length * 251;
    this.elem.width(width);
  };

  return CardContainer;

})();
